config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'home#index'
  get 'home/about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
 belongs_to :user
 has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
 validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # GET /pins
  # GET /pins.json
  def index
   @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build (pins_params)
      respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pins_params)
        format.html { redirect_to @pin, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin } 
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end 
  end
  
  def correct_user
    @pin = current_user.pins.find_by(id: params[:id])
     redirect_to pins_path, notice: "Whatcha doin? ey..tryin to edit this pin!" if @pin.nil? 
  end
    
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
        @pin = Pin.find(params[:id])
    end
    
    def pins_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container">
        
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
            <%= link_to 'TRAYLOR MADE', root_path,class: "navbar-brand" %>
        </div>
        
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Home', root_path, class: 'btn btn-default' %></li>
                <li><%= link_to 'About Me', home_about_path, class: 'btn btn-default' %></li>
                <% if user_signed_in? %>
                <li><%= link_to 'Pins', pins_path, class: 'btn btn-default' %></li>
                <li><%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-default' %></li>
                <li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete, class: 'btn btn-default' %></li>
                <% else %>
                <li><%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-default' %></li>
                <li><%= link_to 'Login', new_user_session_path, class: 'btn btn-default' %></li>
                <% end %>
            </ul>
        </div>
        
    </div>
    
</nav>

app/views/home/about.html.erb
<div class="jumbotron">
<h1>About Necole</h1>

<p>Let's see. To start, she is the best. If the sun ever goes out we need to send her to space to replace it. 
That's how much of an inspiration she is.<br>What else? Oh yeah, she thinks she has the biggest head in the planet 
so there's another reason she resembles the sun. Just kidding! Don't kill me!</p>
<P> Thank you Jesus for your help meon my coding adventure</P>
</div>

app/views/home/index.html.erb
<div class="jumbotron center">
   <h1>Hire Lady B*</h1>

<P> I prmise to make this work for you so you can get back to reigning <br> You are destined to reign</br> :)</p>

<% if user_signed_in? %>
<%= link_to 'New Pin', new_pin_path, class: 'btn btn-default' %>
<%= link_to 'Log Out', destroy_user_session_path, :method => :delete, class: 'btn btn-default' %>
<% else %>
<%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-default' %>
<%= link_to 'Login', new_user_session_path, class: 'btn btn-default' %>
<% end %> 

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'home/header' %>

<div class= "container">

  <% flash.each do |name, msg| %>
    <%= content_tag( :div, msg, class:"alert alert-info") %>
  <% end %>

  <%= yield %>

</div>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :descriptiom %><br>
    <%= f.text_field :description, class:"form-control" %>
  </div>
  
   <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">

  <div class="panel-heading"><h1>Editing Pin</h1></div>
  
    <div class="panel-body">
      <%= render 'form' %>
    </div>
    
    <div class="panel-footer">
        <%= link_to 'Show', @pin, class: 'btn btn-default' %> |
        <%= link_to 'Back', pins_path, class: 'btn btn-default' %>
    </div>
    
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  
  <div class="panel-body">
    
    <% @pins.each do |pin| %>
    
      <%= link_to image_tag(pin.image.url(:thumb)), pin %><br>
      <%= pin.description %><br>
      <% if pin.user == current_user %>
        <%= link_to 'Edit', edit_pin_path(pin), class: 'btn btn-primary' %>
        <%= link_to 'Destroy', pin, class: 'btn btn-primary', method: :delete, data: { confirm: 'Are you sure?' } %><br>
      <% end %>
      <br>
    <% end %>
  </div>
  
  <div class="panel-footer">
  <%= link_to 'New pin', new_pin_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">

  <div class="panel-heading"><h1>New Pin</h1></div>
  
  <div class="panel-body">
      <%= render 'form' %>
  </div>
  
  <div class="panel-footer">
      <%= link_to 'Back', pins_path, class: 'btn btn-default' %>
  </div>
    
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
  
  <div class="panel-body">
  <%= image_tag @pin.image.url(:medium) %><br>
  <%= @pin.description %>
  </div>
  
  <div class="panel-footer">
  <% if @pin.user == current_user %>
  <%= link_to 'Edit', edit_pin_path(@pin), class: 'btn btn-primary' %> |
  <% end %>
  <%= link_to 'Back', pin_path, class: 'btn btn-default' %>
  </div>

</div>